version: '3.8'

services:
  test-identity-db:
    image: postgres
    container_name: test-identity-db
    environment:
      POSTGRES_PASSWORD: 5hGzwu)UuTTlZ-F
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "6591:5432"
    volumes:
      - testapp:/var/lib/postgresql/data
    restart: 
      on-failure
    mem_limit: "2g"
    mem_reservation: "512m"
    cpus: "2"

  test-identity:
    build:
      context: ./
    image: identity8-img
    container_name: test-identity
    command: dotnet TestIndetity8.dll
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: 
      on-failure
    mem_limit: "2g"
    cpus: "2"
    depends_on:
      - test-identity-db

volumes:
  testapp:
